### ISSUE TITLE
APACHE TIKA STARTER PROJECT 

### ISSUE THREAD

**Issue by BilalAM** [MSaifAsif/sample-skeleton-projects#104]
Content and document analysis framework 
**Fun Fact** Primarily used by journalists and investigators with apache lucene for investigating and tracking documents

**Comment by BilalAM** [comment]
in progress : 
https://github.com/BilalAM/apache-tikka-starter

**Comment by MSaifAsif** [comment]
Sounds interesting, can you add a skeleton project for this?

**Comment by BilalAM** [comment]
Check the link I commented

**Comment by BilalAM** [comment]
it is still in progress , just adding and trying out new stuff

**Comment by MSaifAsif** [comment]
looks good. Add it in this repo.

**Comment by MSaifAsif** [comment]
@BilalAM any update ?
