### ISSUE TITLE
Convert project into Grunt/Glup Configurator

### ISSUE THREAD

**Issue by muhammadaliqasmi** [MSaifAsif/sample-skeleton-projects#88]
Convert project into Grunt/Glup Configurator.

**Comment by MSaifAsif** [comment]
Good idea, I'll see what I can do with this one,

**Comment by MSaifAsif** [comment]
@muhammadaliqasmi Please review the current state and let me know regarding any further changes. Projects branch is https://github.com/MSaifAsif/sample-skeleton-projects/tree/gh-pages

**Comment by MSaifAsif** [comment]
marking it done
