### ISSUE TITLE
New Skeleton - Vaadin

### ISSUE THREAD

**Issue by MSaifAsif** [MSaifAsif/sample-skeleton-projects#97]
Add a skeleton project about the Vaadin framework https://vaadin.com/

keep it simple and concise. You are not required to implement everything. Only implement the basic functionalities of some major components, document them and test it enough to make sure that its working. 

**What is a skeleton**
The smallest possible implementation of a framework that runs a hello world cycle either by printing it on the console of displaying it on the browser or showcases basic components of an MVC framework in the simplest way as possible. More details at http://msaifasif.github.io/sample-skeleton-projects/

**Nice to haves**
- Login screen (no authentication required, password can be hardcoded)
- A landing page using basic layout showing some features of Vaadin (tables, grids, etc)
- A short description on how to run it.

**Comment by michaelmdev** [comment]
Is this issue actual ?

**Comment by MSaifAsif** [comment]
What do you mean actual ?

**Comment by michaelmdev** [comment]
There is no code for Vaadin framework in your repo. 
I can provide it, I'm use vaadin everyday.
So question is: Is issue #97 are relevant after 2 years have past ?

**Comment by MSaifAsif** [comment]
@michaelmdev yes that would be awesome. Just create a new folder and create a very small implementation of the project with instructions on how to run it. And for the 2years in the past question, well its never too late :)

**Comment by michaelmdev** [comment]
ok I'll try to PR some @ this weekend

**Comment by MSaifAsif** [comment]
Thanks !
