### ISSUE TITLE
proposing an extended feature in JPA skeleton

### ISSUE THREAD

**Issue by BilalAM** [MSaifAsif/sample-skeleton-projects#98]
in your JPA skeleton (**https://github.com/MSaifAsif/sample-skeleton-projects/tree/master/JPA/src/main/java/com/jpa/dao**) , what if you had more than 1 model class , **creating the individual dao classes for each model can be time consuming** , there should be a utility that **automatically generates the dao classes** for each model like this one below
https://github.com/BilalAM/GenericMongo/blob/master/src/com/data/scaffolder/ScaffolderMain.java
Example usage can be found below link
https://github.com/BilalAM/GenericMongo/blob/master/src/com/data/dao/Program.java

**Comment by MSaifAsif** [comment]
@BilalAM interesting, I will have a look at it in more detail in a couple of days (its too late night here) and then we can get back on this.

**Comment by BilalAM** [comment]
Ok

**Comment by MSaifAsif** [comment]
@BilalAM can you please take a look at this and send a PR ?
